### ISSUE TITLE
Not working with vote sender. (incorrect timestamp)

### ISSUE THREAD

**Issue by InnuendoSA** [UpcraftLP/Voting#3]
I have vote sender on my Spigot hub server that sends the votes to all my other servers.
It works on all my other spigot servers but not my 2 modded servers.

On my 1.10.2(1.10.2-12.18.3.2477) forge server I get this error:

10.09 13:23:20 [Server] Vote-Listener/ERROR [votifier]: Votifier: incorrect vote received:
10.09 13:23:20 [Server] INFO -----------------------------------------------------
10.09 13:23:20 [Server] INFO VOTE
10.09 13:23:20 [Server] INFO Minecraft-MP.com
10.09 13:23:20 [Server] INFO InnuendoSA
10.09 13:23:20 [Server] INFO *.*.*.*(I removed my IP)
10.09 13:23:20 [Server] INFO 1536578603
10.09 13:23:20 [Server] INFO -----------------------------------------------------
10.09 13:23:20 [Server] Vote-Listener/ERROR [votifier]: invalid vote timestamp!
10.09 13:23:20 [Server] INFO java.text.ParseException: Unparseable date: "1536578603"
10.09 13:23:20 [Server] INFO at java.text.DateFormat.parse(Unknown Source) ~[?:1.8.0_181]
10.09 13:23:20 [Server] INFO at com.github.upcraftlp.votifier.net.NetworkListenerThread.run(NetworkListenerThread.java:61) [NetworkListenerThread.class:1.1.2]

On my 1.12.2 forge(1.12.2-14.23.4.2739) server I get this error:

10.09 13:34:49 [Server] Vote-Listener/ERROR [votifier]: Error handling socket connection!
10.09 13:34:49 [Server] INFO java.net.SocketException: Connection reset
10.09 13:34:49 [Server] INFO at java.net.SocketInputStream.read(Unknown Source) ~[?:1.8.0_181]
10.09 13:34:49 [Server] INFO at java.net.SocketInputStream.read(Unknown Source) ~[?:1.8.0_181]
10.09 13:34:49 [Server] INFO at com.github.upcraftlp.votifier.net.NetworkListenerThread.run(NetworkListenerThread.java:47) [NetworkListenerThread.class:1.2.0]

Im not sure why its not working. I am using Votifier on my spigot servers ant it works.
All the vote ports is open on my firewall.

**Comment by UpcraftLP** [comment]
would you mind posting the full log for 1.12.2, as the snippets you provided don't even contain version numbers....

also that 1.10.2 bug is fixed in the 1.12.2 version already, I just want #2 fixed before backporting the changes.

**Comment by InnuendoSA** [comment]
[latest.zip](https://github.com/UpcraftLP/Votifier/files/2366603/latest.zip)
My last log as requested(1.12.2).
1.12.2 is running Forge Votifier v1.2.0 MC1.12.2.
1.10.2 is running Forge Votifier v1.1.2 MC1.8.9 
So on 1.10.2 does that mean I must just wait for a new version for 1.10.2 or I must forget about 1.10.2?

**Comment by Jager67** [comment]
Version 1.2.0
https://pixelmonservers.com

Gives me an error of:

Vote-Listener/ERROR 11/20/2018 00:18:45
00:18:45Error handling socket connection!
Console 11/20/2018 00:18:45
00:18:45javax.crypto.BadPaddingException: Decryption error
at sun.security.rsa.RSAPadding.unpadV15(RSAPadding.java:383) ~[?:1.8.0_181]
at sun.security.rsa.RSAPadding.unpad(RSAPadding.java:294) ~[?:1.8.0_181]
at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:363) ~[sunjce_provider.jar:1.8.0_171]
at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389) ~[sunjce_provider.jar:1.8.0_171]
at javax.crypto.Cipher.doFinal(Cipher.java:2164) ~[?:1.8.0_171]
at com.github.upcraftlp.votifier.util.RSAUtil.decrypt(RSAUtil.java:27) ~[RSAUtil.class:1.2.0]
at com.github.upcraftlp.votifier.net.NetworkListenerThread.run(NetworkListenerThread.java:48) [NetworkListenerThread.class:1.2.0]

**Comment by UpcraftLP** [comment]
@Jager67 see #2 for that
